version: '2'

volumes:
  orderer.mederahealth.com:

networks: 
  fangtu:

    
services:

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.mederahealth.com
    container_name: orderer.mederahealth.com
    networks:
      - fangtu
    extra_hosts:
      - "orderer.mederahealth.com:172.19.60.23"
      - "peer0.yiyuan.mederahealth.com:172.19.60.22"
      - "peer1.yiyuan.mederahealth.com:172.19.60.22"
      - "peer0.shaoyifu.mederahealth.com:172.19.60.20"
      - "peer1.shaoyifu.mederahealth.com:172.19.60.20"