version: '2'

volumes:
  orderer.mederahealth.com:

networks: 
  fangtu:

    
services:

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.mederahealth.com
    container_name: orderer.mederahealth.com
    networks:
      - fangtu
    extra_hosts:
      - "orderer.mederahealth.com:10.214.50.115"
      - "peer0.org1.mederahealth.com:10.214.50.115"
      - "peer1.org1.mederahealth.com:10.214.50.68"