version: '2'

volumes:
  peer0.yiyuan.mederahealth.com:
  peer1.yiyuan.mederahealth.com:

networks: 
  fangtu:

services:

  peer0.yiyuan.mederahealth.com:
    container_name: peer0.yiyuan.mederahealth.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.yiyuan.mederahealth.com
    networks:
      - fangtu
    extra_hosts:
      - "orderer.mederahealth.com:172.19.60.23"
      - "peer1.yiyuan.mederahealth.com:172.19.60.22"
      - "peer0.shaoyifu.mederahealth.com:172.19.60.20"
      - "peer1.shaoyifu.mederahealth.com:172.19.60.20"
  
  peer1.yiyuan.mederahealth.com:
    container_name: peer1.yiyuan.mederahealth.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.yiyuan.mederahealth.com
    networks:
      - fangtu
    extra_hosts:
      - "orderer.mederahealth.com:172.19.60.23"
      - "peer0.yiyuan.mederahealth.com:172.19.60.22"
      - "peer0.shaoyifu.mederahealth.com:172.19.60.20"
      - "peer1.shaoyifu.mederahealth.com:172.19.60.20"
    
  cli.peer0:
    container_name: cli.peer0
    image: hyperledger/fabric-tools:x86_64-1.1.0
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
     # - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.yiyuan.mederahealth.com:37051
      - CORE_PEER_LOCALMSPID=YiyuanMSP
      - CORE_PEER_TLS_ENABLED=false
      # - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/yiyuan.mederahealth.com/peers/peer0.yiyuan.mederahealth.com/tls/server.crt
      # - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/yiyuan.mederahealth.com/peers/peer0.yiyuan.mederahealth.com/tls/server.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/yiyuan.mederahealth.com/peers/peer0.yiyuan.mederahealth.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/yiyuan.mederahealth.com/users/admin@yiyuan.mederahealth.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        # - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - peer0.yiyuan.mederahealth.com
    networks:
      - fangtu
    extra_hosts:
      - "orderer.mederahealth.com:172.19.60.23"
      - "peer0.yiyuan.mederahealth.com:172.19.60.22"
      - "peer1.yiyuan.mederahealth.com:172.19.60.22"
      - "peer0.shaoyifu.mederahealth.com:172.19.60.20"
      - "peer1.shaoyifu.mederahealth.com:172.19.60.20"
  
  cli.peer1:
    container_name: cli.peer1
    image: hyperledger/fabric-tools:x86_64-1.1.0
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
     # - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer1.yiyuan.mederahealth.com:38051
      - CORE_PEER_LOCALMSPID=YiyuanMSP
      - CORE_PEER_TLS_ENABLED=false
      # - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/yiyuan.mederahealth.com/peers/peer1.yiyuan.mederahealth.com/tls/server.crt
      # - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/yiyuan.mederahealth.com/peers/peer1.yiyuan.mederahealth.com/tls/server.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/yiyuan.mederahealth.com/peers/peer1.yiyuan.mederahealth.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/yiyuan.mederahealth.com/users/admin@yiyuan.mederahealth.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        # - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - peer1.yiyuan.mederahealth.com
    networks:
      - fangtu
    extra_hosts:
      - "orderer.mederahealth.com:172.19.60.23"
      - "peer0.yiyuan.mederahealth.com:172.19.60.22"
      - "peer1.yiyuan.mederahealth.com:172.19.60.22"
      - "peer0.shaoyifu.mederahealth.com:172.19.60.20"
      - "peer1.shaoyifu.mederahealth.com:172.19.60.20"
  